
package ru.anokhin.jaxws.client;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookService", targetNamespace = "http://impl.service.jaxws.anokhin.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns ru.anokhin.jaxws.client.BookSoapDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://impl.service.jaxws.anokhin.ru/", className = "ru.anokhin.jaxws.client.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://impl.service.jaxws.anokhin.ru/", className = "ru.anokhin.jaxws.client.UpdateResponse")
    @Action(input = "http://impl.service.jaxws.anokhin.ru/BookService/updateRequest", output = "http://impl.service.jaxws.anokhin.ru/BookService/updateResponse")
    public BookSoapDto update(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<String> arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        XMLGregorianCalendar arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns ru.anokhin.jaxws.client.BookSoapDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://impl.service.jaxws.anokhin.ru/", className = "ru.anokhin.jaxws.client.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://impl.service.jaxws.anokhin.ru/", className = "ru.anokhin.jaxws.client.CreateResponse")
    @Action(input = "http://impl.service.jaxws.anokhin.ru/BookService/createRequest", output = "http://impl.service.jaxws.anokhin.ru/BookService/createResponse")
    public BookSoapDto create(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        XMLGregorianCalendar arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.anokhin.jaxws.client.BookSoapDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://impl.service.jaxws.anokhin.ru/", className = "ru.anokhin.jaxws.client.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://impl.service.jaxws.anokhin.ru/", className = "ru.anokhin.jaxws.client.FindByIdResponse")
    @Action(input = "http://impl.service.jaxws.anokhin.ru/BookService/findByIdRequest", output = "http://impl.service.jaxws.anokhin.ru/BookService/findByIdResponse")
    public BookSoapDto findById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.util.List<ru.anokhin.jaxws.client.BookSoapDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByFilter", targetNamespace = "http://impl.service.jaxws.anokhin.ru/", className = "ru.anokhin.jaxws.client.FindByFilter")
    @ResponseWrapper(localName = "findByFilterResponse", targetNamespace = "http://impl.service.jaxws.anokhin.ru/", className = "ru.anokhin.jaxws.client.FindByFilterResponse")
    @Action(input = "http://impl.service.jaxws.anokhin.ru/BookService/findByFilterRequest", output = "http://impl.service.jaxws.anokhin.ru/BookService/findByFilterResponse")
    public List<BookSoapDto> findByFilter(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        XMLGregorianCalendar arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        XMLGregorianCalendar arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        Integer arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        Integer arg6);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteBookById", targetNamespace = "http://impl.service.jaxws.anokhin.ru/", className = "ru.anokhin.jaxws.client.DeleteBookById")
    @ResponseWrapper(localName = "deleteBookByIdResponse", targetNamespace = "http://impl.service.jaxws.anokhin.ru/", className = "ru.anokhin.jaxws.client.DeleteBookByIdResponse")
    @Action(input = "http://impl.service.jaxws.anokhin.ru/BookService/deleteBookByIdRequest", output = "http://impl.service.jaxws.anokhin.ru/BookService/deleteBookByIdResponse")
    public boolean deleteBookById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

}
